### ISSUE TITLE
Remove echo=FALSE for necessary code. 

### ISSUE THREAD

**Issue by tylersimko** [davidkane9/PPBDS#271]
We got a question on Slack about this code in Section 1.3: 

`ggplot(data = gapminder_07, mapping = aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point()`

The code itself is perfect, but on line 955 of `01-visualization.Rmd` we're hiding the definition of `gapminder_07` with an `echo=FALSE`. 

```{r echo=FALSE}
gapminder_07 <- gapminder %>% 
                    filter(year == 2007)
```

I'm not sure how common this is, but I think we should include any code that's necessary to run example code in the book. That why, students can type all of the examples along as they read the book.

**Comment by tylersimko** [comment]
@davidkane9 `flights_counted` in Chapter 1 is another example of this:

`flights_counted <- flights %>% 
  group_by(carrier) %>% 
  summarize(number = n())`

**Comment by davidkane9** [comment]
Thanks! Both fixed.
