### ISSUE TITLE
Language in RPubs Section

### ISSUE THREAD

**Issue by tylersimko** [davidkane9/PPBDS#278]
In the RPubs section of the book, we're saying to create an "R Markdown project." Since students think of "project" in terms of RStudio projects, I've had a few get confused about where to find the "R Markdown Project" button.

https://davidkane9.github.io/PPBDS/tools.html#how-to-use-rpubs

I suggest we delete the word project and just call them R Markdown files. File --> New File --> R Markdown

**Comment by davidkane9** [comment]
Fixed!
